[[plugins]]
repo = 'Shougo/dein.vim' # Required
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/neocomplete'
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'Shougo/vimshell'
[[plugins]]
repo = 'Shougo/neco-vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'scrooloose/nerdtree.git'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# color scheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'vim-scripts/Wombat'

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'

# all-lang
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'szw/vim-tags'

# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'

# scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
[[plugins]]
repo = 'vim-scripts/JavaDecompiler.vim'

# haskell
[[plugins]]
repo = 'ujihisa/neco-ghc'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# PHP
[[plugins]]
repo = 'joonty/vdebug'

# SQL
[[plugins]]
repo = 'vim-scripts/SQLUtilities'
[[plugins]]
repo = 'vim-scripts/Align' # SQLUtilitiesで必要

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'

# TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'

# Yaml
[[plugins]]
repo = 'mrk21/yaml-vim'

# Toml
[[plugins]]
repo = 'cespare/vim-toml'

# twig
[[plugins]]
repo = 'evidens/vim-twig'
